userNumber1 = prompt('Please enter first number');
userNumber2 = prompt('Please enter second number');
console.log (typeof 0);
additon = parseInt(userNumber1) + parseInt (userNumber2);
console.log(additon);
subtraction = parseInt(userNumber1) - parseInt (userNumber2);
console.log(subtraction);
multiplication = parseInt(userNumber1) * parseInt (userNumber2);
console.log(multiplication);
division = parseInt(userNumber1) / parseInt (userNumber2);
console.log(division);